### ISSUE TITLE
Overflow in GAS_MCL and GAS_MCLI

### ISSUE THREAD

**Issue by mediremi** [FuelLabs/fuel-vm#192]
Both [`GAS_MCL`](https://github.com/FuelLabs/fuel-vm/blob/c5a1a246adbdd581cd13c05d058bb35831c79ade/src/interpreter/gas/consts.rs#L91) and [`GAS_MCLI`](https://github.com/FuelLabs/fuel-vm/blob/c5a1a246adbdd581cd13c05d058bb35831c79ade/src/interpreter/gas/consts.rs#L92) fail to handle multiply with overflow.

**`GAS_MCL`:**
```
thread '<unnamed>' panicked at 'attempt to multiply with overflow', src/interpreter/gas/consts.rs:91:58
stack backtrace:
   0: rust_begin_unwind
             at /rustc/23e21bdd25026e2839ebe946c2a937c1904887d2/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/23e21bdd25026e2839ebe946c2a937c1904887d2/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/23e21bdd25026e2839ebe946c2a937c1904887d2/library/core/src/panicking.rs:48:5
   3: core::ops::function::FnOnce::call_once
   4: fuel_vm::interpreter::executors::instruction::<impl fuel_vm::interpreter::Interpreter<S>>::_instruction
   5: fuel_vm::interpreter::executors::instruction::<impl fuel_vm::interpreter::Interpreter<S>>::execute
   6: fuel_vm::interpreter::executors::main::<impl fuel_vm::interpreter::Interpreter<S>>::run
   7: fuel_vm::interpreter::executors::main::<impl fuel_vm::interpreter::Interpreter<S>>::transact
```

**`GAS_MCLI`:**
```
thread '<unnamed>' panicked at 'attempt to multiply with overflow', src/interpreter/gas/consts.rs:92:60
stack backtrace:
   0: rust_begin_unwind
             at /rustc/23e21bdd25026e2839ebe946c2a937c1904887d2/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/23e21bdd25026e2839ebe946c2a937c1904887d2/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/23e21bdd25026e2839ebe946c2a937c1904887d2/library/core/src/panicking.rs:48:5
   3: core::ops::function::FnOnce::call_once
   4: fuel_vm::interpreter::executors::instruction::<impl fuel_vm::interpreter::Interpreter<S>>::_instruction
   5: fuel_vm::interpreter::executors::instruction::<impl fuel_vm::interpreter::Interpreter<S>>::execute
   6: fuel_vm::interpreter::executors::main::<impl fuel_vm::interpreter::Interpreter<S>>::run
   7: fuel_vm::interpreter::executors::main::<impl fuel_vm::interpreter::Interpreter<S>>::transact
   8: fuel_vm::transactor::Transactor<S>::transact
   9: fuel_vm::memory_client::MemoryClient::transact
```

Here's test cases for both (found with the fuzzing script introduced in https://github.com/FuelLabs/fuel-vm/pull/188):

```rust
use fuel_vm::prelude::*;

#[test]
fn multiply_with_overflow_gas_mcl() {
    let mut client = MemoryClient::default();

    let gas_price = 0;
    let gas_limit = 100_000;
    let maturity = 0;
    let height = 0;
    let params = ConsensusParameters::DEFAULT;

    let mut tx = Transaction::script(
        gas_price,
        gas_limit,
        maturity,
        vec![],
        vec![
            28,
            84,
            92,
            16,
            39,
            41,
            80,
            0,
        ],
        vec![],
        vec![],
        vec![],
    )
    .check(height, &params)
    .expect("failed to generate a checked tx");

    client.transact(tx);
}

#[test]
fn multiply_with_overflow_gas_mcli() {
    let mut client = MemoryClient::default();

    let gas_price = 0;
    let gas_limit = 100_000;
    let maturity = 0;
    let height = 0;
    let params = ConsensusParameters::DEFAULT;

    let mut tx = Transaction::script(
        gas_price,
        gas_limit,
        maturity,
        vec![],
        vec![
            28,
            255,
            255,
            255,
            112,
            255,
            255,
        ],
        vec![],
        vec![],
        vec![],
    )
    .check(height, &params)
    .expect("failed to generate a checked tx");

    client.transact(tx);
}
```

cc @vlopes11 @Voxelot

**Comment by Voxelot** [comment]
related: https://github.com/FuelLabs/fuel-vm/issues/170

**Comment by Dentosal** [comment]
Unable to reproduce anymore. Checked the code around MCL(I) and it isn't doing unchecked arithmetic anymore.
