### ISSUE TITLE
Running too many Sway unit tests causes `failed to check tx: TransactionScriptLength`

### ISSUE THREAD

**Issue by FossilFrank** [FuelLabs/fuel-vm#438]
I'm running some unit tests written in Sway, and it appears that the presence of unit tests is causing the following error:

```
  Finished debug in 15.993886833s
   library libraries
      Bytecode size: 1347340 bytes
   Running 7 tests
thread 'thread 'thread '<unnamed><unnamed><unnamed>' panicked at '' panicked at '' panicked at 'failed to check tx: TransactionScriptLengthfailed to check tx: TransactionScriptLength', ', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/fuel-vm-0.26.3/src/checked_transaction/builder.rs/Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/fuel-vm-0.26.3/src/checked_transaction/builder.rsfailed to check tx: TransactionScriptLength::', 2828::/Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/fuel-vm-0.26.3/src/checked_transaction/builder.rs14:
14note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
28
:14
thread '<unnamed>' panicked at 'failed to check tx: TransactionScriptLength', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/fuel-vm-0.26.3/src/checked_transaction/builder.rs:28:14
thread '<unnamed>' panicked at 'failed to check tx: TransactionScriptLength', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/fuel-vm-0.26.3/src/checked_transaction/builder.rs:28:14
thread '<unnamed>' panicked at 'failed to check tx: TransactionScriptLength', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/fuel-vm-0.26.3/src/checked_transaction/builder.rs:28:14
thread '<unnamed>' panicked at 'failed to check tx: TransactionScriptLength', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/fuel-vm-0.26.3/src/checked_transaction/builder.rs:28:14
```

The file has a number of unit tests, and I can get rid of this error by commenting out any 2 of them.

**Comment by Dentosal** [comment]
Unable to reproduce. Manual review makes it look impropable that this is still an issue. Feel free to reopen if the issue persists.
